from datetime import date, datetime
from typing import Protocol

from app.models import Account, AuditEvent, Budget, Category, RefreshToken, Transaction, User


class UserRepository(Protocol):
    def get_by_id(self, user_id: str) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def add(self, user: User) -> None: ...


class RefreshTokenRepository(Protocol):
    def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    def add(self, refresh_token: RefreshToken) -> None: ...
    def has_newer_token(self, user_id: str, created_after: datetime) -> bool: ...
    def list_active_by_user(self, user_id: str) -> list[RefreshToken]: ...


class AccountRepository(Protocol):
    def get_owned(self, user_id: str, account_id: str) -> Account | None: ...
    def list_for_user(self, user_id: str, include_archived: bool) -> list[Account]: ...
    def add(self, account: Account) -> None: ...


class CategoryRepository(Protocol):
    def get_owned(self, user_id: str, category_id: str) -> Category | None: ...
    def list_for_user(self, user_id: str, include_archived: bool, category_type: str | None) -> list[Category]: ...
    def add(self, category: Category) -> None: ...


class TransactionRepository(Protocol):
    def get_owned(self, user_id: str, transaction_id: str) -> Transaction | None: ...
    def list_for_user(
        self,
        user_id: str,
        include_archived: bool,
        tx_type: str | None,
        account_id: str | None,
        category_id: str | None,
        from_date: date | None,
        to_date: date | None,
    ) -> list[Transaction]: ...
    def add(self, transaction: Transaction) -> None: ...


class BudgetRepository(Protocol):
    def get_owned(self, user_id: str, budget_id: str) -> Budget | None: ...
    def list_for_user_month_range(self, user_id: str, from_month: str, to_month: str) -> list[Budget]: ...
    def add(self, budget: Budget) -> None: ...


class AuditEventRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...
    def list_for_user(
        self,
        user_id: str,
        *,
        from_created_at: datetime | None,
        to_created_at: datetime | None,
    ) -> list[AuditEvent]: ...
